[package]
name = "luminance-glutin"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]

[dependencies]
gl = "0.9"
glutin = "0.12"
luminance = "0.25"
luminance-windowing = "0.1"
